"""initial schema with operational tables

Revision ID: b4632cefdc42
Revises: 
Create Date: 2026-06-13 17:03:17.994614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4632cefdc42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_version')
    )
    op.create_table('operational_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_reference', sa.String(length=128), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('stations',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=5), nullable=True),
    sa.Column('layer', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trains',
    sa.Column('train_number', sa.String(length=16), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('train_number')
    )
    op.create_table('corridor_edges',
    sa.Column('edge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_station_id', sa.String(length=10), nullable=False),
    sa.Column('to_station_id', sa.String(length=10), nullable=False),
    sa.Column('base_time_min', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('base_run_seconds', sa.Integer(), nullable=True),
    sa.Column('min_headway_seconds', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('direction_group', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_table('rescheduling_runs',
    sa.Column('rescheduling_run_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('predictor_name', sa.String(length=64), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('commit_window_minutes', sa.Integer(), nullable=False),
    sa.Column('objective_before', sa.Float(), nullable=True),
    sa.Column('objective_after', sa.Float(), nullable=True),
    sa.Column('secondary_delay_before_seconds', sa.Integer(), nullable=True),
    sa.Column('secondary_delay_after_seconds', sa.Integer(), nullable=True),
    sa.Column('compute_time_ms', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['operational_snapshots.snapshot_id'], ),
    sa.PrimaryKeyConstraint('rescheduling_run_id')
    )
    op.create_table('station_aliases',
    sa.Column('alias_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('alias_code', sa.String(length=20), nullable=False),
    sa.Column('alias_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alias_id')
    )
    with op.batch_alter_table('station_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_aliases_alias_code'), ['alias_code'], unique=True)

    op.create_table('timetable_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('train_number', sa.String(length=16), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('run_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['train_number'], ['trains.train_number'], ),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('train_number', 'service_date', name='uq_timetable_runs_train_date')
    )
    op.create_table('train_locations',
    sa.Column('train_id', sa.String(length=20), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.Column('current_station', sa.String(length=10), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('gtfs_trip_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['current_station'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('train_id')
    )
    op.create_table('delay_predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('p50_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('p90_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['operational_snapshots.snapshot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('snapshot_id', 'run_id', 'horizon_minutes', 'model_version', name='uq_delay_predictions_snap_run_horizon_model')
    )
    op.create_table('disruption_events',
    sa.Column('disruption_id', sa.String(length=36), nullable=False),
    sa.Column('disruption_type', sa.String(length=32), nullable=False),
    sa.Column('station_code', sa.String(length=16), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['corridor_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['station_code'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('disruption_id')
    )
    op.create_table('live_train_states',
    sa.Column('live_state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_station_code', sa.String(length=16), nullable=True),
    sa.Column('next_station_code', sa.String(length=16), nullable=True),
    sa.Column('current_segment_id', sa.Integer(), nullable=True),
    sa.Column('segment_progress', sa.Float(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['current_segment_id'], ['corridor_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['last_station_code'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['next_station_code'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('live_state_id'),
    sa.UniqueConstraint('run_id', 'observed_at', name='uq_live_states_run_time')
    )
    op.create_table('rescheduling_actions',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rescheduling_run_id', sa.String(length=36), nullable=False),
    sa.Column('action_sequence', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('station_code', sa.String(length=16), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['corridor_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['rescheduling_run_id'], ['rescheduling_runs.rescheduling_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_runs.run_id'], ),
    sa.ForeignKeyConstraint(['station_code'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('action_id'),
    sa.UniqueConstraint('rescheduling_run_id', 'action_sequence', name='uq_rescheduling_actions_run_seq')
    )
    op.create_table('timetable_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('station_code', sa.String(length=16), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_dwell_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_code'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('run_id', 'stop_sequence', name='uq_timetable_events_run_seq')
    )
    op.create_table('detected_conflicts',
    sa.Column('conflict_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rescheduling_run_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('first_run_id', sa.String(length=36), nullable=False),
    sa.Column('second_run_id', sa.String(length=36), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('conflict_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conflict_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['corridor_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['first_run_id'], ['timetable_runs.run_id'], ),
    sa.ForeignKeyConstraint(['rescheduling_run_id'], ['rescheduling_runs.rescheduling_run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_action_id'], ['rescheduling_actions.action_id'], ),
    sa.ForeignKeyConstraint(['second_run_id'], ['timetable_runs.run_id'], ),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_conflicts')
    op.drop_table('timetable_events')
    op.drop_table('rescheduling_actions')
    op.drop_table('live_train_states')
    op.drop_table('disruption_events')
    op.drop_table('delay_predictions')
    op.drop_table('train_locations')
    op.drop_table('timetable_runs')
    with op.batch_alter_table('station_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_aliases_alias_code'))

    op.drop_table('station_aliases')
    op.drop_table('rescheduling_runs')
    op.drop_table('corridor_edges')
    op.drop_table('trains')
    op.drop_table('stations')
    op.drop_table('operational_snapshots')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
